### ISSUE TITLE
Implement script context functions

### ISSUE THREAD

**Issue by AriFordsham** [mlabs-haskell/hedgehog-plutus-simple#27]
Implement The following typed holes:
- `Hedgehog.Plutus.ScriptContext`
  - [x] `plutusScriptContext` 
- `Hedgehog.Plutus.TxTest`
  - [x] `scriptContext`
  - [x] `resolveOmitted`

`scriptContext` should call `resolveOmitted` to fulfil the requirements outlined in the comment for `txTest`.

**Comment by Geometer1729** [comment]
closed by #31
