### ISSUE TITLE
CI for deferred typed holes

### ISSUE THREAD

**Issue by AriFordsham** [mlabs-haskell/hedgehog-plutus-simple#35]
- Create an additional flake output that builds with `-fdefer-typed-holes`
- Configure Hercules to build both

This will give us an additional green tick for `defer-typed-holes`.

https://docs.hercules-ci.com/hercules-ci-agent/evaluation#attributes-herculesCI.onPush
https://mlabs-corp.slack.com/archives/C0290MGE23D/p1676909814213239?thread_ts=1676905274.718879&cid=C0290MGE23D

**Comment by Geometer1729** [comment]
Closed by #42
