### ISSUE TITLE
Implement functions for adjunction architecture

### ISSUE THREAD

**Issue by AriFordsham** [mlabs-haskell/hedgehog-plutus-simple#7]
Implement functions currently written as typed holes on the `ari/onion` branch.

This list is subject to change. Currently these are:

- `Tx.hs`
  - [x] `balanceTx`
  - [x]  `confirmBalanced`
  - [x] `spend`
  - [x]   `toSimpleModelTx`
  - [x]   `toLedgerTx`
  - [x] `scriptPurposeTx`
  - [x]   `toLedgerScriptPurpose`

- [ ] Complete function `txRunScript` in `TestSingleScript.hs`

You can use the implementation in psm `Mock.hs` to guide you.

hps uses a branch of psm that exposes hidden modules, mainly the `Fork.*` hierarchy. This is intended as a temporary fix, so avoid using these in favour of regular psm functions where possible, but use them where necessary.

Please PR each function individually, so our branches stay in sync.

**Comment by AriFordsham** [comment]
I have changed the signature of `balanceTx` to allow true randomness.

I have also added two more functions which I think will be useful - `confirmBalanced` and `spend`. I would assume `balanceTx` should be implemented using `spend` (as well as `evaluateTransactionBalance` as per the review).

**Comment by AriFordsham** [comment]
@Geometer1729 Can you check off what is complete here?

**Comment by Geometer1729** [comment]
`spend` got renamed to `spendWhere` when we added the predicate argument, but is complete.
